server:
  port: 8080
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: transaction_route
          uri: lb://transaction-service
          predicates:
            - Path=/api/transaction/**
        - id: account_route
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
        - id: notification_route
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
